### ISSUE TITLE
WorkThread error

### ISSUE THREAD

**Issue by kanatm287** [Doggie52/Lean-Batch-Launcher#2]
var engine = new Engine( leanEngineSystemHandlers, leanEngineAlgorithmHandlers, false );
engine.Run( job, algorithmManager, assemblyPath );

Error	CS7036	argument missing "workerThread" из "Engine.Run(AlgorithmNodePacket, AlgorithmManager, string, WorkerThread)".	Instance

**Comment by Doggie52** [comment]
**Спасибо for reporting!**

I will need to look at this. It could be very simple or require a total re-write of the Launcher. I will not be able to look at this in **at least a month from now** due to other commitments.

If you are very keen to get this fixed, maybe you can see where `workerThread` is coming from and just add it as a parameter to `Engine()`?

**Comment by kanatm287** [comment]
Hi seems works after adding WorkerThread.Instance

engine.Run( job, algorithmManager, assemblyPath, WorkerThread.Instance);

**Comment by Doggie52** [comment]
Thanks for your help with this!
